version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8327:5000"  # Map port 8327 on the host to port 5000 in the container
    environment:
      - FLASK_ENV=production  # Set Flask environment to production
    restart: always  # Restart policy for production
